baseURL: "https://www.mamasspecialty.com"
languageCode: "en-us"
title: "Mama's Specialty (Specialty Coffee & Homemade Food)"

params:
  description: "Mama's Specialty, Homemade Food, Specialty Coffee, Family owned restaurant Samui"
  customCSS:
    - "css/custom.css"
  defaultTheme: "dark"
