baseURL: "https://www.charoenwatthana.org/"
languageCode: "en-us"
title: "Charoen Watthana Initiative"

params:
  description: "Charoen Watthana for a better world"
  customCSS:
    - "css/custom.css"
  defaultTheme: "dark"
